<?php

return [
    'groups' => [
        'Amigos',
        'Amigos Aza',
        'Amigos Mary',
        'Amigos Zu',
        'Extras',
        'Familia Aza',
        'Familia Mary',
    ],
    'prefixes' => [
        'Sr.',
        'Sra.',
        'Señorita',
        'Joven',
        'Lic.',
        'Mtra.',
        'Mtro.',
        'Profr.',
        'Profra.',
        'Miss',
    ],
    'categories' => [
        'Real',
        'Probable',
    ],
    'statuses' => [
        'Considerado',
        'Invitacion Enviada',
        'Pendiente',
        'Confirmado',
        'Rechazado',
        'No contesto',
        'Por definir',
    ],
    'followups' => [
        'Pendiente',
        'Enviado',
        'Respondio',
        'No aplica',
    ],
    'sponsors' => [
        'Vino',
        'Violin',
        'Brindis',
        'DJ',
        'Cabina de fotos',
        'Chambelan',
        'Corona',
        'Zapatillas',
        'Salon',
        'Banda',
        'Pastel',
        'Recuerdos',
        'Regalo sorpresa',
        'Adorno',
        'Velacion',
        'Salon y Foto',
    ],
    'table_types' => [
        'Principal',
        'Familiar',
        'General',
        'Niños',
        'Jóvenes',
        'Staff',
        'Reservada',
    ],
    'table_shapes' => [
        'Redonda',
        'Rectangular',
        'Cuadrada',
        'Imperial',
    ],
];
